version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: ruby:2.7.1
      - image: circleci/mysql:5.7
        name: 'db'
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USERNAME: root
      MYSQL_HOST: db
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          paths:
            - /usr/local/bundle
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
