version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: ruby:2.7.1
        environment:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: app_test
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
    steps:
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

workflows:
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
